name: Build and deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_ID }}
          password: ${{ secrets.ACR_SECRET }}

      - name: Build Container
        run: docker build -t ${{ secrets.ACR_IMAGE }} .
      
      - name: Push Container
        run: docker push ${{ secrets.ACR_IMAGE }}